prefix = "rc."
description = "Chess bot created and maintained by Lucas Roy."
games_file = "./games.json"
history_file = "./history.json"
profiles_file = "./profiles.json"
token = "" # put your token here
home_id = 0 # guild id that the bot will call "home"
home_invite = "" # invite URL to the home server
developers = ["Lucas Roy", "Daniel Sepulveda"] # list of whoever is working on the bot
timezone = "EST" # abbreviated timezone for the bots local region
autosave = 1800 # interval (in seconds) that the bot saves all data to disk
timeout = 259200 # maximum time (in seconds) before a game times out 
min_move_cutoff = 8 # minimum number of moves a resigned game can have in history
